fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(
                tauri_build::AppManifest::new()
                    .commands(&[
                        "speak_text",
                        "set_safe_mode",
                        "start_screen_preview",
                        "stop_screen_preview",
                        "create_action_proposal",
                        "approve_action_proposal",
                        "reject_action_proposal",
                        "set_window_size",
                        "debug_log",
                    ]),
            ),
    )
    .unwrap();
}
