[mypy]
ignore_missing_imports = True
disable_error_code = type-arg, assignment, attr-defined, arg-type, return-value, var-annotated, typeddict-item, typeddict-unknown-key, operator, index, call-arg, dict-item, union-attr, func-returns-value, has-type, import-untyped
