/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, run `npm run generate:types` in frontend-v2.
 */

export type Server =
  | AssistantMessageEvent
  | ChunkEvent
  | StatusEvent
  | VoiceStateEvent
  | VoiceTranscriptEvent
  | VoiceWakeWordEvent
  | VoiceErrorEvent
  | VoiceTtsStateEvent
  | VoiceStartedEvent
  | SafeModeChangedEvent
  | ScreenAssistStateEvent
  | ActionProposalEvent
  | ActionProposalResultEvent
  | InterruptEvent
  | ToolExecutionEvent
  | RouterInfoEvent
  | ModelInfoEvent
  | CloudUsageEvent
  | CloudBudgetWarningEvent
  | ContextSummarizedEvent
  | MemoryUpdatedEvent
  | FileStatusEvent
  | BrowserPageContextEvent
  | CoherenceRetryStartedEvent
  | CoherenceRetryCompletedEvent
  | ResponseCoherenceEvent;
export type Type = "assistant.message";
export type Id = string | null;
export type Content = string | null;
export type Id1 = string | null;
export type Type1 = string | null;
export type Content1 = string | null;
export type ToolCalls = unknown[] | null;
export type ToolName = string | null;
export type ToolCallId = string | null;
export type ModelUsed = string | null;
export type TokenUsage = {
  [k: string]: unknown;
} | null;
export type Type2 = "chunk";
export type Content2 = string;
export type Type3 = "status";
export type Content3 = string;
export type Type4 = "voice.state";
export type State = "idle" | "recording" | "transcribing" | "speaking" | "interrupted" | "approval_pending";
export type Type5 = "voice.transcript";
export type Text = string;
export type IsFinal = boolean;
export type Confidence = number | null;
export type Type6 = "voice.wake_word";
export type Phrase = string;
export type Confidence1 = number | null;
export type Type7 = "voice.error";
export type Message = string;
export type Code = string | null;
export type Type8 = "voice.tts_state";
export type Speaking = boolean;
export type UtteranceId = string | null;
export type Type9 = "voice.started";
export type Mode = "wake_word" | "ptt";
export type Type10 = "safe_mode.changed";
export type Mode1 = "normal" | "safe_readonly" | "safe_confirmed_exec" | "safe_isolated";
export type Type11 = "screen_assist.state";
export type Mode2 = "off" | "preview" | "annotating";
export type Source = "screen" | "window" | "region";
export type PreviewPath = string | null;
export type Type12 = "action.proposal";
export type Id2 = string;
export type Summary = string;
export type Source1 = "screen_assist" | "voice" | "system";
export type CreatedAt = number;
export type Status = "pending" | "approved" | "rejected";
export type Type13 = "action.proposal.result";
export type Id3 = string;
export type Status1 = "approved" | "rejected";
export type Type14 = "interrupt";
export type Interrupts = unknown[];
export type Type16 = "tool_execution";
export type Status2 = "running" | "success" | "error";
export type ToolName2 = string;
export type ToolCallId1 = string | null;
export type Input = string | null;
export type Output = string | null;
export type Error = string | null;
export type RiskLabel1 = string | null;
export type RiskConfidence1 = number | null;
export type RiskRationale1 = string | null;
export type RemediationHint1 = string | null;
export type Duration = number | null;
export type Filename = string;
export type Url = string;
export type Kind = "interactive" | "static";
export type MimeType = string;
export type Type17 = "router_info";
export type Type18 = "model_info";
export type Model = string;
export type ModelUsed1 = string | null;
export type Swapping = boolean | null;
export type TokenUsage1 = {
  [k: string]: unknown;
} | null;
export type FallbackChain = FallbackChainItem[] | null;
export type Model1 = string;
export type Status3 = string;
export type Reason = string;
export type DurationMs = number;
export type Type19 = "cloud_usage";
export type Turn = {
  [k: string]: unknown;
} | null;
export type Session = {
  [k: string]: unknown;
} | null;
export type Budget = {
  [k: string]: unknown;
} | null;
export type WarningThresholds = number[] | null;
export type Type20 = "cloud_budget_warning";
export type Threshold = number;
export type UsedPct = number;
export type UsedTokens = number;
export type DailyTokenLimit = number;
export type EstimatedCostUsd = number | null;
export type Type21 = "context_summarized";
export type Summary1 = string;
export type Takeaways = string[];
export type MessagesCompressed = number;
export type TokensFreed = number;
export type Type22 = "memory_updated";
export type ThreadId = string | null;
export type Type23 = "file_status";
export type Name = string | null;
export type Status4 = string | null;
export type Chunks = number | null;
export type Error1 = string | null;
export type Type24 = "browser.page_context";
export type Url1 = string | null;
export type Title = string | null;
export type Text1 = string | null;
export type Selection = string | null;
export type Intent = string | null;
export type Type25 = "coherence_retry_started";
export type Attempt = number | null;
export type OriginalConfidence = number | null;
export type Type26 = "coherence_retry_completed";
export type Type27 = "response_coherence";
export type Coherent = boolean;
export type Confidence2 = number;
export type DurationMs1 = number;
export type Reason1 = string | null;
export type CorrelationId = string | null;
export type Client =
  | UserMessageEvent
  | StopClientEvent
  | SecurityApprovalClientEvent
  | AskUserResponseClientEvent
  | PlanReviewResponseClientEvent;
export type Type28 = "user.message";
export type CorrelationId1 = string | null;
export type Id4 = string;
export type Content4 = string;
export type Message1 = string | null;
export type Files =
  | {
      [k: string]: string;
    }[]
  | null;
export type ProjectId = string | null;
export type PersonaId = string | null;
export type Source2 = ("text" | "voice") | null;
export type Type29 = "stop";
export type Type30 = "security_approval";
export type Approved = boolean;
export type CorrelationId2 = string | null;
export type Type31 = "ask_user_response";
export type CorrelationId3 = string | null;
export type Type32 = "plan_review_response";
export type Approved1 = boolean;
export type Feedback = string | null;
export type CorrelationId4 = string | null;

export interface ProtocolEvents {
  server: Server;
  client: Client;
  [k: string]: unknown;
}
export interface AssistantMessageEvent {
  type?: Type;
  id?: Id;
  content?: Content;
  message?: AssistantMessagePayload | null;
  [k: string]: unknown;
}
export interface AssistantMessagePayload {
  id?: Id1;
  type?: Type1;
  content?: Content1;
  tool_calls?: ToolCalls;
  tool_name?: ToolName;
  tool_call_id?: ToolCallId;
  model_used?: ModelUsed;
  token_usage?: TokenUsage;
  [k: string]: unknown;
}
export interface ChunkEvent {
  type?: Type2;
  content: Content2;
  [k: string]: unknown;
}
export interface StatusEvent {
  type?: Type3;
  content: Content3;
  [k: string]: unknown;
}
export interface VoiceStateEvent {
  type?: Type4;
  state: State;
  [k: string]: unknown;
}
export interface VoiceTranscriptEvent {
  type?: Type5;
  text: Text;
  is_final: IsFinal;
  confidence?: Confidence;
  [k: string]: unknown;
}
export interface VoiceWakeWordEvent {
  type?: Type6;
  phrase: Phrase;
  confidence?: Confidence1;
  [k: string]: unknown;
}
export interface VoiceErrorEvent {
  type?: Type7;
  message: Message;
  code?: Code;
  [k: string]: unknown;
}
export interface VoiceTtsStateEvent {
  type?: Type8;
  speaking: Speaking;
  utterance_id?: UtteranceId;
  [k: string]: unknown;
}
export interface VoiceStartedEvent {
  type?: Type9;
  mode: Mode;
  [k: string]: unknown;
}
export interface SafeModeChangedEvent {
  type?: Type10;
  mode: Mode1;
  [k: string]: unknown;
}
export interface ScreenAssistStateEvent {
  type?: Type11;
  mode: Mode2;
  source: Source;
  preview_path?: PreviewPath;
  [k: string]: unknown;
}
export interface ActionProposalEvent {
  type?: Type12;
  proposal: ActionProposalPayload;
  [k: string]: unknown;
}
export interface ActionProposalPayload {
  id: Id2;
  summary: Summary;
  source: Source1;
  created_at: CreatedAt;
  status: Status;
  [k: string]: unknown;
}
export interface ActionProposalResultEvent {
  type?: Type13;
  id: Id3;
  status: Status1;
  [k: string]: unknown;
}
export interface InterruptEvent {
  type?: Type14;
  interrupts: Interrupts;
  [k: string]: unknown;
}
export interface ToolExecutionEvent {
  type?: Type16;
  status: Status2;
  tool_name: ToolName2;
  tool_call_id?: ToolCallId1;
  input?: Input;
  output?: Output;
  error?: Error;
  risk_label?: RiskLabel1;
  risk_confidence?: RiskConfidence1;
  risk_rationale?: RiskRationale1;
  remediation_hint?: RemediationHint1;
  duration?: Duration;
  chart_artifact?: ChartArtifact | null;
  [k: string]: unknown;
}
export interface ChartArtifact {
  filename: Filename;
  url: Url;
  kind: Kind;
  mime_type: MimeType;
  [k: string]: unknown;
}
export interface RouterInfoEvent {
  type?: Type17;
  metadata: Metadata;
  [k: string]: unknown;
}
export interface Metadata {
  [k: string]: unknown;
}
export interface ModelInfoEvent {
  type?: Type18;
  model: Model;
  model_used?: ModelUsed1;
  swapping?: Swapping;
  token_usage?: TokenUsage1;
  fallback_chain?: FallbackChain;
  [k: string]: unknown;
}
export interface FallbackChainItem {
  model: Model1;
  status: Status3;
  reason: Reason;
  duration_ms: DurationMs;
  [k: string]: unknown;
}
export interface CloudUsageEvent {
  type?: Type19;
  turn?: Turn;
  session?: Session;
  budget?: Budget;
  warning_thresholds?: WarningThresholds;
  [k: string]: unknown;
}
export interface CloudBudgetWarningEvent {
  type?: Type20;
  threshold: Threshold;
  used_pct: UsedPct;
  used_tokens: UsedTokens;
  daily_token_limit: DailyTokenLimit;
  estimated_cost_usd?: EstimatedCostUsd;
  [k: string]: unknown;
}
export interface ContextSummarizedEvent {
  type?: Type21;
  summary: Summary1;
  takeaways: Takeaways;
  messages_compressed: MessagesCompressed;
  tokens_freed: TokensFreed;
  [k: string]: unknown;
}
export interface MemoryUpdatedEvent {
  type?: Type22;
  thread_id?: ThreadId;
  [k: string]: unknown;
}
export interface FileStatusEvent {
  type?: Type23;
  name?: Name;
  status?: Status4;
  chunks?: Chunks;
  error?: Error1;
  [k: string]: unknown;
}
export interface BrowserPageContextEvent {
  type?: Type24;
  url?: Url1;
  title?: Title;
  text?: Text1;
  selection?: Selection;
  intent?: Intent;
  [k: string]: unknown;
}
export interface CoherenceRetryStartedEvent {
  type?: Type25;
  attempt?: Attempt;
  original_confidence?: OriginalConfidence;
  [k: string]: unknown;
}
export interface CoherenceRetryCompletedEvent {
  type?: Type26;
  [k: string]: unknown;
}
export interface ResponseCoherenceEvent {
  type?: Type27;
  coherent: Coherent;
  confidence: Confidence2;
  duration_ms: DurationMs1;
  reason?: Reason1;
  correlation_id?: CorrelationId;
  [k: string]: unknown;
}
export interface UserMessageEvent {
  type?: Type28;
  correlation_id?: CorrelationId1;
  id: Id4;
  content: Content4;
  message?: Message1;
  files?: Files;
  project_id?: ProjectId;
  persona_id?: PersonaId;
  source?: Source2;
  [k: string]: unknown;
}
export interface StopClientEvent {
  type?: Type29;
  [k: string]: unknown;
}
export interface SecurityApprovalClientEvent {
  type?: Type30;
  approved: Approved;
  correlation_id?: CorrelationId2;
  [k: string]: unknown;
}
export interface AskUserResponseClientEvent {
  type?: Type31;
  answer: Answer;
  correlation_id?: CorrelationId3;
  [k: string]: unknown;
}
export interface Answer {
  [k: string]: unknown;
}
export interface PlanReviewResponseClientEvent {
  type?: Type32;
  approved: Approved1;
  feedback?: Feedback;
  correlation_id?: CorrelationId4;
  [k: string]: unknown;
}

export type ServerEvent = ProtocolEvents["server"];
export type ClientEvent = ProtocolEvents["client"];
