#!/usr/bin/env python3
import json
import os
import subprocess
from pathlib import Path
from pydantic import TypeAdapter

ROOT_DIR = Path(__file__).resolve().parent.parent
FRONTEND_DIR = ROOT_DIR / "frontend-v2"
GEN_TS_PATH = FRONTEND_DIR / "src" / "types" / "protocol.generated.ts"
PROTOCOL_TS = FRONTEND_DIR / "src" / "types" / "protocol.ts"


def main():
    import sys

    sys.path.insert(0, str(ROOT_DIR))

    from src.api.ws.schemas import ServerEvent, ClientEvent

    from pydantic import BaseModel

    class ProtocolEvents(BaseModel):
        server: ServerEvent
        client: ClientEvent

    protocol_adapter = TypeAdapter(ProtocolEvents)
    protocol_schema = protocol_adapter.json_schema()
    protocol_schema["title"] = "ProtocolEvents"

    schema_path = ROOT_DIR / ".protocol_schema.json"

    with open(schema_path, "w") as f:
        json.dump(protocol_schema, f)

    print("Generating TypeScript interfaces from Pydantic schemas...")

    cmd = f"npx -y json-schema-to-typescript {schema_path} --bannerComment ''"

    try:
        ts_output = subprocess.check_output(
            cmd, shell=True, cwd=FRONTEND_DIR, text=True
        )
    except subprocess.CalledProcessError as e:
        print(f"Error running json-schema-to-typescript: {e}")
        sys.exit(1)

    schema_path.unlink()

    # Extract the types we actually want exported: ServerEvent and ClientEvent
    # The generated file will have `export interface ProtocolEvents { server: ServerEvent; client: ClientEvent; }`
    # We can just leave it as is, or we can export the types explicitly if needed.

    final_output = f"""/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, run `npm run generate:types` in frontend-v2.
 */

{ts_output.strip()}

export type ServerEvent = ProtocolEvents["server"];
export type ClientEvent = ProtocolEvents["client"];
"""

    with open(GEN_TS_PATH, "w") as f:
        f.write(final_output)

    print(f"Successfully generated {GEN_TS_PATH}")


if __name__ == "__main__":
    main()
