"""
State Definition for the Local Cowork Agent.

This module defines the `AgentState` TypedDict used by LangGraph to maintain
conversation history, execution mode, and other contextual flags.
"""

import operator
from typing import Annotated, TypedDict, Sequence
from langchain_core.messages import BaseMessage

from langgraph.channels.delta import DeltaChannel
from langgraph.graph.message import add_messages, _messages_delta_reducer


class AgentState(TypedDict):
    """
    Represents the internal state of the Local Cowork Agent during execution.
    It relies entirely on standard Python dicts to be easily serializable by Langgraph checks.
    """

    # The active conversation/reasoning history
    # Using DeltaChannel to incrementally save changes and avoid O(N^2) bloat.
    messages: Annotated[Sequence[BaseMessage], DeltaChannel(_messages_delta_reducer)]

    # Internal scratchpad/status that doesn't need to be kept forever in messages
    current_task: str | None

    # Any structured facts discovered in this specific thread (to be sent to Mem0 eventually)
    extracted_facts: Annotated[list[str], operator.add]

    execution_plan: str | None  # Multi-step JSON plan generated by the local router
    # Arbitrary context retrieved from VectorDB/Mem0 before reasoning
    long_term_context: str | None

    # Execution mode: 'tools_off' or 'tools_on'
    mode: str | None

    # When False, complex path binds tools without web_search (UI "Web search" off).
    web_search_enabled: bool | None

    # Chat response style: normal | learning | concise | explanatory | formal
    response_style: str | None

    # Project ID to associate this conversation with a specific project
    project_id: str | None

    # Thread identifier (set from config at graph entry, used by audit log + memory)
    thread_id: str | None

    # Track if any tool execution was vetted/approved by security node
    execution_approved: bool | None

    # Routing decision: 'simple' or 'complex-cloud'
    route: str | None
    # Model provenance: 'small-local', 'large-cloud', or either with '-fallback' suffix
    model_used: str | None
    memory_context: str | None  # Formatted context string
    knowledge_context: str | None  # Synthesized facts from previous web searches
    needs_memory_retrieval: bool | None  # Router gate: run vector retrieval when True
    scenario_id: str | None  # L2/L3 scenario: pentest | research
    scenario_context: str | None  # Loaded scenario markdown block
    persona: str | None  # Persona summary string
    persona_id: str | None  # Active persona ID (e.g. 'coder', 'writer', 'default')
    pentest_current_phase: str | None  # Track phase for context truncation

    # Toolbox names selected by the router (e.g. ["web_search", "file_ops"] or ["all"])
    selected_toolboxes: list[str] | None

    # Dynamic token budget — set by the router based on request complexity
    token_budget: int | None

    # Secure cyclic tool flow state
    pending_tool_calls: bool | None
    pending_tool_names: Annotated[list[str], operator.add]
    security_decision: str | None  # 'approved' | 'denied'
    security_reason: str | None

    # Cloud cost tracking — token usage from DeepSeek API
    api_tokens_used: dict | None  # {"prompt_tokens": int, "completion_tokens": int}

    # Whether the router asked for user clarification this turn
    router_clarification_used: bool | None

    # Router metadata for telemetry — populated by router_node on each routing decision
    router_metadata: dict | None

    # Skill matched by the router (proactive, outside HITL path)
    # Dict with keys: name, toolbox, score — set when a strong skill match is found
    skill_matched: dict | None

    # Names of tools explicitly denied by human reviewer (appended across turns)
    denied_tools: list[str] | None

    # ── Scope clarification (scope_clarify node) ─────────────────────────
    # User-approved requirements from scope_clarify HITL
    clarified_scope: dict | None

    # ── Plan review (plan_review node) ───────────────────────────────────
    # Whether plan_review was approved (True), denied (False), or skipped (None)
    plan_review_approved: bool | None
    # Optional feedback from the human reviewer
    plan_review_feedback: str | None

    # Track consecutive turns within browser_local to trigger auto-escalation
    _browser_local_turns: int | None

    # Fallback chain for telemetry — ordered list of model attempts in complex_llm_node
    fallback_chain: list[dict] | None

    # ── Auto-summarize state ───────────────────────────────────────────
    # Current active token count (used for summarization threshold check)
    active_tokens: int | None
    # Context window size of the active model
    context_window: int | None
    # Cumulative tokens summarized in this thread (for observability)
    summarized_tokens: int | None
    # Takeaway strings from the most recent summarization
    summary_takeaways: list[str] | None
    # Payload for the context_summarized WS event
    context_summarized_event: dict | None

    # ── Response Coherence & Turn Metrics ────────────────────────────────
    turn_start_time: float | None
    response_confidence: float | None
    response_coherence: dict | None
    turn_duration_ms: int | None

    # ── Internal Continuation Flags ───────────────────────────────────────
    _cutoff_pending: bool | None
    _cutoff_round: int | None
    web_search_suggested: bool | None
    # Coherence retry counter — incremented by coherence_retry_node; bounds the
    # cycle coherence_check → coherence_retry → complex_llm to max_retries.
    _coherence_retry_round: int | None
    # Last coherence score observed before the retry; surfaced in WS event for UX
    coherence_retry_reason: str | None
